# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Https < Formula
  desc "HTTP Stream CLI"
  homepage "https://github.com/nwtgck/https"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nwtgck/https/releases/download/v0.1.1/https-0.1.1-darwin-arm64.tar.gz"
      sha256 "5126bd278c27b94145bd366229b52d182daa2dbea61a16311e94924816717d4f"

      def install
        bin.install "https"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/https/releases/download/v0.1.1/https-0.1.1-darwin-amd64.tar.gz"
      sha256 "21407624f0c9ff8f7d151767874beda0e9c48f352be2eb1d4209139a0531efd1"

      def install
        bin.install "https"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/https/releases/download/v0.1.1/https-0.1.1-linux-arm64.tar.gz"
      sha256 "fac132a4488a6f13360023e82ef50f0680685ddd1a033ed6891e3bc4a1b8c7e8"

      def install
        bin.install "https"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/https/releases/download/v0.1.1/https-0.1.1-linux-amd64.tar.gz"
      sha256 "cdf1fe2289fb68d27291ede203274e6e3f9499466dad872f0094cb0c62879672"

      def install
        bin.install "https"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/https/releases/download/v0.1.1/https-0.1.1-linux-armv6.tar.gz"
      sha256 "bda9cfc49bd8e68f4f622f1b76441f77ad431ba85e74d7f85e86a8d3259412e5"

      def install
        bin.install "https"
      end
    end
  end
end
