# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Https < Formula
  desc "HTTP Stream CLI"
  homepage "https://github.com/nwtgck/https"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nwtgck/https/releases/download/v0.2.0/https-0.2.0-darwin-arm64.tar.gz"
      sha256 "8892f26f884557298a0890338ba9f1c7dc81416664434c5ccc78330bf84fac22"

      def install
        bin.install "https"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/https/releases/download/v0.2.0/https-0.2.0-darwin-amd64.tar.gz"
      sha256 "ea2f642019ff1906e0fd9fb891b6f2c69dbf38fb90772af8314947889da3ef89"

      def install
        bin.install "https"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/https/releases/download/v0.2.0/https-0.2.0-linux-amd64.tar.gz"
      sha256 "ec1cc785b9653256217f6e437805fee2960e1f4ce83fa0342ed55a22e862a6a5"

      def install
        bin.install "https"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/https/releases/download/v0.2.0/https-0.2.0-linux-armv6.tar.gz"
      sha256 "72de4c5b9c0fc2a6d79c62ae7c87344b6ef31c5b65e06291e6a554db64a508ea"

      def install
        bin.install "https"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/https/releases/download/v0.2.0/https-0.2.0-linux-arm64.tar.gz"
      sha256 "2a2137ccbacd481461186933f139d269321ad3e9081a17e7881f0051e394c044"

      def install
        bin.install "https"
      end
    end
  end
end
